### ISSUE TITLE
Prompts for tasks

### ISSUE THREAD

**Issue by yulonglin** [tau-nlp/scrolls#3]
For the your tasks, are the "input" column the full input passed into the models? Did you add any additional prompting for the models provided in the leaderboard?

For example, for GovReport, did you (or were the teams who submitted allowed to) do something like the following?

```
Original Text:
<"input" column of GovReport>

Summary:
<"output" column of GovReport / output of model>
```

Or is there no additional prompting:

```
<"input" column of GovReport>
<"output" column of GovReport / output of model>
```

**Comment by UriSha** [comment]
Hi,

Thanks for your question.

SCROLLS is model/prompt agnostic, you are allowed to use prompts if you want.
In our baselines, we didn't use prompts.

I hope that helps.

**Comment by yulonglin** [comment]
Thanks! That's helpful :)
