### ISSUE TITLE
QuALITY validation result of LED

### ISSUE THREAD

**Issue by jxiw** [tau-nlp/scrolls#7]
I try to get the validation result of LED in QuALITY. After running your code, I get the following results.

```
1024 27.9003
4096 23.9693
16384 20.326
```

Those results are very bad. Are those results consistent with what you have?

Thanks.

**Comment by UriSha** [comment]
Hi,

I don’t have the validation scores of our initial baseline. However, as you can see in Table 2 from the paper, the LED baseline did get close to random results on QuALITY, which matches your numbers.

By the way, feel free to make a private submission to the leaderboard to receive your test scores. Just remember that  you'll need to create a valid submission file containing (potentially mock) predictions for each ID across all tasks. I've explained the process [here](https://github.com/tau-nlp/scrolls/issues/1#issuecomment-1154103425).

You are also welcome to checkout [Efficient Long-Text Understanding with Short-Text Models](https://arxiv.org/abs/2208.00748)  (code [here](https://github.com/Mivg/SLED)) where we got some better numbers.

**Comment by UriSha** [comment]
Hi,

I don’t have the validation scores of our initial baseline. However, as you can see in Table 2 from the paper, the LED baseline did get close to random results on QuALITY, which matches your numbers.

By the way, feel free to make a private submission to the leaderboard to receive your test scores. Just remember that you'll need to create a valid submission file containing (potentially mock) predictions for each ID across all tasks. I've explained the process https://github.com/tau-nlp/scrolls/issues/1#issuecomment-1154103425.

**Comment by UriSha** [comment]
Hi,

I don’t have the validation scores of our initial baseline. However, as you can see in Table 2 from the paper, the LED baseline did get close to random results on QuALITY, which matches your numbers.

By the way, feel free to make a private submission to the leaderboard to receive your test scores. Just remember that you'll need to create a valid submission file containing (potentially mock) predictions for each ID across all tasks. I've explained the process [here](https://github.com/tau-nlp/scrolls/issues/1#issuecomment-1154103425).
